mv src\app.tsx src\App.tsx
mv src\main.tsx src\main.tsx
mv src\components\common\button.tsx src\components\common\Button.tsx
mv src\components\common\button.module.css src\components\common\Button.module.css
mv src\components\common\card.tsx src\components\common\Card.tsx
mv src\components\common\card.module.css src\components\common\Card.module.css
mv src\components\common\input.tsx src\components\common\Input.tsx
mv src\components\common\input.module.css src\components\common\Input.module.css
mv src\components\common\select.tsx src\components\common\Select.tsx
mv src\components\common\select.module.css src\components\common\Select.module.css
mv src\components\common\datatable.tsx src\components\common\DataTable.tsx
mv src\components\common\datatable.module.css src\components\common\DataTable.module.css
mv src\components\common\priceblock.tsx src\components\common\PriceBlock.tsx
mv src\components\common\priceblock.module.css src\components\common\PriceBlock.module.css
mv src\components\common\statusbadge.tsx src\components\common\StatusBadge.tsx
mv src\components\common\statusbadge.module.css src\components\common\StatusBadge.module.css
mv src\components\layout\appsidebar.tsx src\components\layout\AppSidebar.tsx
mv src\components\layout\topbar.tsx src\components\layout\Topbar.tsx
mv src\components\layout\applayout.tsx src\components\layout\AppLayout.tsx
mv src\components\layout\layout.module.css src\components\layout\Layout.module.css
mv src\components\layout\adminsidebar.tsx src\components\layout\AdminSidebar.tsx
mv src\components\layout\adminlayout.tsx src\components\layout\AdminLayout.tsx
mv src\pages\auth\login.tsx src\pages\auth\Login.tsx
mv src\pages\auth\register.tsx src\pages\auth\Register.tsx
mv src\pages\auth\auth.module.css src\pages\auth\Auth.module.css
mv src\pages\shipper\dashboard.tsx src\pages\shipper\Dashboard.tsx
mv src\pages\shipper\dashboard.module.css src\pages\shipper\Dashboard.module.css
mv src\pages\shipper\myshipments.tsx src\pages\shipper\MyShipments.tsx
mv src\pages\shipper\shipmentdetail.tsx src\pages\shipper\ShipmentDetail.tsx
mv src\pages\shipper\createshipment.tsx src\pages\shipper\CreateShipment.tsx
mv src\pages\shipper\receivedoffers.tsx src\pages\shipper\ReceivedOffers.tsx
mv src\pages\shipper\negotiation.tsx src\pages\shipper\Negotiation.tsx
mv src\pages\shipper\tripslist.tsx src\pages\shipper\TripsList.tsx
mv src\pages\shipper\triptrack.tsx src\pages\shipper\TripTrack.tsx
mv src\pages\shipper\triprating.tsx src\pages\shipper\TripRating.tsx
mv src\pages\shipper\wallet.tsx src\pages\shipper\Wallet.tsx
mv src\pages\shipper\profile.tsx src\pages\shipper\Profile.tsx
mv src\pages\admin\admindashboard.tsx src\pages\admin\AdminDashboard.tsx
mv src\pages\admin\adminapprovals.tsx src\pages\admin\AdminApprovals.tsx
